services:
  - type: web
    name: visa-slot-checker-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

  - type: worker
    name: visa-slot-checker-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
